### ISSUE TITLE
Step2: invoke AWS Nuke

### ISSUE THREAD

**Issue by gfou-al** [ministryofjustice/modernisation-platform#1645]
## User Story

Related story: #1523

Example github action implementation: https://github.com/ministryofjustice/github-actions/tree/main/terraform-static-analysis

AWS Nuke is documented at https://github.com/rebuy-de/aws-nuke

As documented in the AWS Nuke documentation, accounts that have the word prod in them will be automatically skipped (performance-hub-preproduction, etc).

In the github action implementation use the docker image `quay.io/rebuy/aws-nuke`.

Use the nuke-config.yml generated from the previous step and pass it to AWS Nuke

See also

- https://github.com/rebuy-de/aws-nuke
- https://www.sumologic.com/blog/reduce-aws-bill-nuke/

## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [x] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
The working nuke-config.yml is:

```
---
feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    EC2Instance: true
    CloudformationStack: true
  force-delete-lightsail-addons: true

regions:
  - "eu-west-2"

account-blocklist:
  - "<account number>" # performance-hub-preproduction
  - "<account number>" # performance-hub-production
  - "<account number>" # xhibit-portal-preproduction
  - "<account number>" # xhibit-portal-production

resource-types:
  # don't nuke IAM users
  excludes:
    - ACMCertificate
    - EC2DHCPOption
    - EC2InternetGateway
    - EC2InternetGatewayAttachment
    - EC2NetworkACL
    - EC2RouteTable
    - EC2Subnet
    - EC2VPC
    - GuardDutyDetector
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMInstanceProfile
    - IAMInstanceProfileRole
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMPolicy
    - IAMRole
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMSAMLProvider
    - IAMServerCertificate
    - IAMServiceSpecificCredential
    - IAMSigningCertificate
    - IAMUser
    - IAMUserAccessKey
    - IAMUserGroupAttachment
    - IAMUserPolicy
    - IAMUserPolicyAttachment
    - IAMUserSSHPublicKey
    - IAMVirtualMFADevice
    - S3Object
    - SecurityHub
    - WAFv2WebACL

accounts:
  "236861075084": # cooker-development
    presets:
      - "common"
  "348456244381": # sprinkler-development
    presets:
      - "common"

presets:
  common:
    filters:
      AWSBackupPlan:
        - property: tag:component
          value: "secure-baselines"
      AWSBackupVault:
        - property: tag:component
          value: "secure-baselines"
      EC2RouteTable:
        - property: tag:component
          value: "secure-baselines"
      EC2VPC:
        - property: tag:component
          value: "secure-baselines"
      EC2NetworkACL:
        - property: tag:component
          value: "secure-baselines"
      KMSKey:
        - property: tag:component
          value: "secure-baselines"
      S3Bucket:
        - property: tag:component
          value: "secure-baselines"
      EC2InternetGatewayAttachment:
        - property: tag:vpc:component
          value: "secure-baselines"
      AccessAnalyzer:
        - property: tag:component
          value: "secure-baselines"
      SNSTopic:
        - property: tag:component
          value: "secure-baselines"
      EC2SecurityGroup:
        - property: tag:component
          value: "secure-baselines"
      EC2DHCPOption:
        - property: tag:component
          value: "secure-baselines"
      SSMParameter:
        - property: tag:component
          value: "delegate-access"
      ConfigServiceConfigRule:
        - type: glob
          value: "securityhub-*"
        - type: glob
          value: "FMManagedShieldConfigRule*"
```
