### ISSUE TITLE
Refactor NACLs to prevent East-West traffic and allow North-South

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2010]
## User Story

We want to redesign our Network Firewall and NACLs so that we are not preventing traffic in 2 places.  Currently we have to open up NACLs and the Firewall to allow traffic in from the Transit Gateway.

This is part of redesigning our networking in and around the network firewall and connection with the PTTP transit gateway.

## Value

Simplify our networking, make issues easier to troubleshoot, make adding new connectivity easier, make errors less likely.

### Hypothesis 
If we open the NACLs to North-South traffic and restrict to East-West
Then we will only manage ingress to the platform in one place, but keep restrictions on East-West traffic.

### Proposal
Redesign the NACLs, something like this:

NACL rules
1. Allow traffic from one MP subnet set cross VPC to another - configured via json/yaml (see example below)
2. Deny all MP VPC ranges
3. Allow private ranges
4. Deny all traffic

Example inter VPC rule:
```
rules:
rule:
   subnet1: hmpps-development-general-data
   subnet2: hmcts-development-general-data
rule:
   subnet1: laa-production-general-private
   subnet2: hmcts-production-general-data
```

This entry in json/yaml would generate allow all traffic both ways between these subnets

## Definition of done

- [ ] NACLs refactored
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
