### ISSUE TITLE
Update all workflows to include slack notification

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#5000]
## User Story

As a modernisation-platform user
I expect to be notified in slack of any failed pipeline that belongs to Modernisation Platform
So that I am informed and can act on it.

The notification is to be sent out for every `push` event on the `main` branch.

## User Type(s)

Modernisation Platform Engineer

## Value

Better awareness of breaking changes and a faster time to find issues and respond to them.

### Proposal
Get a list of workflows that are missing this feature and add [a similar block](https://github.com/ministryofjustice/modernisation-platform/blob/75270c8ff911fc6060f5d16a2a9ca74035d65e1b/.github/workflows/core-vpc-development-deployment.yml#L173) to the one below to all workflows to include a slack notification when a workflow fails.
```
      - name: Slack failure notification
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: |
            {"blocks":[{"type": "section","text": {"type": "mrkdwn","text": ":no_entry: Failed GitHub Action:"}},{"type": "section","fields":[{"type": "mrkdwn","text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"},{"type": "mrkdwn","text": "*Job:*\n${{ github.job }}"},{"type": "mrkdwn","text": "*Repo:*\n${{ github.repository }}"}]}]}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        if: ${{ failure() }}
```

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
