### ISSUE TITLE
Restrict Terraform Apply from Running on Branches/Pull Requests in Environments Repo

### ISSUE THREAD

**Issue by sukeshreddyg** [ministryofjustice/modernisation-platform#9293]
### User Story

As a user creating a branch or pull request in the Modernisation Platform Environments Repository,
I expect to be unable to perform destructive operations through CI/CD, such as Terraform Apply,
so that all destructive changes require peer review before execution.

### Value / Purpose

Currently, users with write access to the Modernisation Platform Environments repository can bypass the peer review process by modifying GitHub Actions workflows, allowing them to execute destructive actions directly. This occurs due to open OIDC permissions assigned to the role assumed by the pipelines.

The objective of this work is to ensure that peer reviews are strictly enforced before any destructive changes are applied to the platform. Implementing a separation of permissions between different GitHub Actions roles will prevent unauthorized or unreviewed destructive operations from occurring.

### Context / Background

This issue was identified as a risk while analyzing the [security concerns around the environments workflows](https://github.com/ministryofjustice/modernisation-platform-security/issues/34). Addressing this risk ensures that all Terraform Apply operations undergo proper approval processes.

### Additional Information

Introduce two separate GitHub Actions roles:

**1. github-action-plan**

- Read-only permissions
- Can generate Terraform Plans but cannot apply changes

**2. github-action-apply**

- Read permissions + ability to assume **MemberInfrastructureAccess** role
- Can apply changes, but only after explicit approval

### Definition of Done

- [ ] I am unable to run Terraform Apply on branches and pull requests by modifying the reusable workflow files
- [ ] CI/CD processes continue to work as usual

**Comment by mikereiddigital** [comment]
Ref the ticket for the MP repo - https://github.com/ministryofjustice/modernisation-platform/issues/8078

**Comment by mikereiddigital** [comment]
Blocked due to a ramshare issues affecting sprinkler and cooker that's impacting the terraform-member-environments workflow.

```
Error: no matching RAM Resource Share found

  with module.ram-principal-association[0].data.aws_ram_resource_share.secondary,
  on ../../modules/ram-principal-association/main.tf line 23, in data "aws_ram_resource_share" "secondary":
  23: data "aws_ram_resource_share" "secondary" {
```

https://github.com/ministryofjustice/modernisation-platform/actions/runs/21672576206/job/62484065780?pr=12429

**Comment by mikereiddigital** [comment]
Above PR resolved the issue.

**Comment by mikereiddigital** [comment]
Using as reference the plan and apply roles as deployed to modernisation-platform-account but amended with new names: - https://github.com/ministryofjustice/modernisation-platform/blob/issue/9293/terraform/environments/sprinkler/testing_roles.tf

Also using a heavily modified version of the sprinkler deploy, reusable strategy & reusable plan apply workflows in environments to test the use of the plans - https://github.com/ministryofjustice/modernisation-platform-environments/tree/issue/9293-workflow-changes/.github/workflows

**Comment by mikereiddigital** [comment]
The goals:

1. Existing PR functionality continues - users able to plan and apply to dev & test from non-main branch. 
2. Existing Deploy/Destroy feature continues for non-prod accounts.
3. For preprod & prod accounts, apply/deploy only from main. 
4. OIDC roles used by workflows can only run from the main branch.

Plan:

1. New variant of the "github-actions pole & policies for use by workflows running in a non-main context. (i.e. not refs/heads/main) but which can only be run against accounts that are *development, *test and *sandbox. 

2. Add the subject_claim of github-actions role to be limited to `refs/heads/main`. 

3. Amend the reusable_terraform_plan_apply & components variants to use the correct role depending on the environment input.

Key consideration will be the deployment plan as it will impact all member accounts.

**Comment by mikereiddigital** [comment]
Issue whereby a number of roles that the github-actions role assumes all have trust relationships that (correctly) restrict what other roles can assume it. e.g. MemberInfrastructureAccess. We will need to implement a change whereby these trust relationships are updated prior to any further testing. This then requires agreement on the new role name.

As github-actions-dev-test is already taken, I'm going to suggest `github-actions-terraform-featurebranch`. Will raise with the team tomorrow morning.

Secondly will also raise tomorrow the question of removing the means to deploy into dev & test accounts without an approved PR. This is a significant change to the scope of functionality of the platform for non-prod work.

**Comment by mikereiddigital** [comment]
Have scoped the workflow changes. This is less than originally expected and can be limited to determining the role assumed based on the value of the `environment` variable obtained in from the strategy job. 

https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/.github/workflows/reusable_terraform_components_plan_apply.yml#L104

Which is then amended to:

```
      - name: Configure AWS Credentials (non-prod)
        if: inputs.environment == 'sandbox' || inputs.environment == 'development' || inputs.environment == 'test'
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708  # v5.1.1
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions-terraform-nonprod"
          role-session-name: githubactionsrolesession-nonprod
          aws-region: "eu-west-2"

      - name: Configure AWS Credentials (preprod/prod)
        if: inputs.environment == 'preproduction' || inputs.environment == 'production'
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708  # v5.1.1
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: "eu-west-2"
```

**Comment by mikereiddigital** [comment]
Similarly, if we want to restrict the workflow_dispatch trigger so that it can only be run from main:

```
  guard-main-for-dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Fail if not main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow_dispatch may only be run from main (got: $GITHUB_REF)" >&2
          exit 1
```
